<a href="https://colab.research.google.com/github/sir-iko/sir-iko/blob/main/Garment_worker_productivity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('garments_worker_productivity.csv')
dataset = dataset.drop(['date', 'wip', 'quarter'], axis=1)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
dataset = dataset.reset_index(drop=True)

In [4]:
print(dataset)

      department        day  team  targeted_productivity    smv  over_time  \
0         sweing   Thursday     8                   0.80  26.16       7080   
1     finishing    Thursday     1                   0.75   3.94        960   
2         sweing   Thursday    11                   0.80  11.41       3660   
3         sweing   Thursday    12                   0.80  11.41       3660   
4         sweing   Thursday     6                   0.80  25.90       1920   
...          ...        ...   ...                    ...    ...        ...   
1192   finishing  Wednesday    10                   0.75   2.90        960   
1193   finishing  Wednesday     8                   0.70   3.90        960   
1194   finishing  Wednesday     7                   0.65   3.90        960   
1195   finishing  Wednesday     9                   0.75   2.90       1800   
1196   finishing  Wednesday     6                   0.70   2.90        720   

      incentive  idle_time  idle_men  no_of_style_change  no_of

In [5]:
dataset.head()

department       day  team  targeted_productivity    smv  over_time  \
0      sweing  Thursday     8                   0.80  26.16       7080   
1  finishing   Thursday     1                   0.75   3.94        960   
2      sweing  Thursday    11                   0.80  11.41       3660   
3      sweing  Thursday    12                   0.80  11.41       3660   
4      sweing  Thursday     6                   0.80  25.90       1920   

   incentive  idle_time  idle_men  no_of_style_change  no_of_workers  \
0         98        0.0         0                   0           59.0   
1          0        0.0         0                   0            8.0   
2         50        0.0         0                   0           30.5   
3         50        0.0         0                   0           30.5   
4         50        0.0         0                   0           56.0   

   actual_productivity  
0             0.940725  
1             0.886500  
2             0.800570  
3             0.800570  
4             0.800382

In [6]:
dataset.isna().sum()

department               0
day                      0
team                     0
targeted_productivity    0
smv                      0
over_time                0
incentive                0
idle_time                0
idle_men                 0
no_of_style_change       0
no_of_workers            0
actual_productivity      0
dtype: int64

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False, dtype='float'), [0, 1, 2, 3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False, dtype='float'), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 0 0 59.0]
 [1.0 0.0 1.0 ... 0 0 8.0]
 [1.0 0.0 0.0 ... 0 0 30.5]
 ...
 [0.0 1.0 0.0 ... 0 0 8.0]
 [0.0 1.0 0.0 ... 0 0 15.0]
 [0.0 1.0 0.0 ... 0 0 6.0]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [11]:
print(X_train)

[[1.0 0.0 1.0 ... 0 0 18.0]
 [1.0 0.0 0.0 ... 0 0 57.0]
 [1.0 0.0 0.0 ... 0 0 30.5]
 ...
 [1.0 0.0 0.0 ... 0 1 51.0]
 [1.0 0.0 0.0 ... 0 0 56.0]
 [1.0 0.0 0.0 ... 0 0 54.0]]


In [12]:
print(y_train)

[0.89219444 0.75006805 0.80057049 0.41083333 0.55543056 0.8
 0.5375     0.80007184 0.59114168 0.70061823 0.70071042 0.7504
 0.95018596 0.90808081 0.82718654 0.70744643 0.80014981 0.75039551
 0.8471     0.560625   0.97186667 0.80039322 0.41083333 0.85013677
 0.90013569 0.85056949 0.82714744 0.93686111 0.66068329 0.63604938
 0.67324528 0.80084242 0.32813158 0.80098039 0.70045989 0.671875
 0.81011111 0.7005569  0.87115    0.60022985 0.60098291 0.67666667
 0.75035613 1.00044602 0.44996491 0.40324216 0.35063299 0.65708333
 0.75045066 0.80047051 0.95311005 0.98802469 0.75007932 0.800125
 0.50006192 0.90032111 0.85036207 0.60036969 1.00023041 0.93041667
 0.97081667 0.80035194 0.85050231 0.70017039 0.70042414 0.68106061
 0.84545833 0.57951149 0.59862745 0.58204546 0.77333333 0.87
 0.625625   0.28704167 0.75034846 0.50080172 0.5046875  0.75065172
 1.00001855 0.26369382 0.92868056 0.38579167 0.271875   0.85036207
 0.86888889 0.64630682 0.80011582 0.98719697 0.77333333 0.59487179
 0.70005833 0.98

In [13]:
print(X_test)

[[1.0 0.0 0.0 ... 0 0 34.0]
 [0.0 1.0 0.0 ... 0 0 22.0]
 [1.0 0.0 1.0 ... 0 0 10.0]
 ...
 [1.0 0.0 0.0 ... 0 0 57.0]
 [1.0 0.0 0.0 ... 0 0 56.5]
 [1.0 0.0 0.0 ... 0 0 33.0]]


In [14]:
print(y_test)

[0.80040196 0.99992424 0.96410606 0.64025    0.60044751 0.70051357
 0.88592593 0.41211983 0.70009556 0.97186667 0.75039551 0.75079701
 0.55034971 0.36266667 0.50052809 0.92160494 0.81361111 0.60027327
 0.76884722 0.83375    0.70061403 0.43632639 0.54996943 0.75040623
 0.7866     0.86037037 0.80080864 0.800125   0.79456667 0.75047368
 0.80003139 0.74916667 0.31385281 0.80098039 0.85056949 0.6253125
 0.85036458 0.60128    0.80027383 0.85013677 0.7005731  0.90296296
 0.90012976 0.70025078 0.75035613 0.79996322 0.91037879 0.85814394
 0.79210417 0.60022419 0.84506944 0.75309753 0.80034377 0.56825959
 0.67666667 0.97186667 1.00001855 0.80026322 0.8000345  0.2565
 0.80098039 0.60127841 0.85117411 0.919125   0.53166667 0.95515151
 0.72693333 0.70065965 0.850045   0.80002056 0.65059649 0.75065101
 0.63466667 0.40896035 0.35030172 0.80027969 0.75005736 0.75075
 0.7505931  0.57831439 0.90014481 0.80354167 0.64998056 0.65854167
 0.80007652 0.32996488 0.75039551 0.70006981 1.00060228 0.36531871
 0.

In [15]:
dataset.head()

department       day  team  targeted_productivity    smv  over_time  \
0      sweing  Thursday     8                   0.80  26.16       7080   
1  finishing   Thursday     1                   0.75   3.94        960   
2      sweing  Thursday    11                   0.80  11.41       3660   
3      sweing  Thursday    12                   0.80  11.41       3660   
4      sweing  Thursday     6                   0.80  25.90       1920   

   incentive  idle_time  idle_men  no_of_style_change  no_of_workers  \
0         98        0.0         0                   0           59.0   
1          0        0.0         0                   0            8.0   
2         50        0.0         0                   0           30.5   
3         50        0.0         0                   0           30.5   
4         50        0.0         0                   0           56.0   

   actual_productivity  
0             0.940725  
1             0.886500  
2             0.800570  
3             0.800570  
4             0.800382

In [16]:
quarter_index = 0
for i in range(X_train.shape[0]):
    if X_train[i, quarter_index] == 'Quarter1':
        X_train[i, quarter_index] = 1
    elif X_train[i, quarter_index] == 'Quarter2':
        X_train[i, quarter_index] = 2
    elif X_train[i, quarter_index] == 'Quarter3':
        X_train[i, quarter_index] = 3
    elif X_train[i, quarter_index] == 'Quarter4':
        X_train[i, quarter_index] = 4

for i in range(X_test.shape[0]):
    if X_test[i, quarter_index] == 'Quarter1':
        X_test[i, quarter_index] = 1


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
print(X_train)

[[ 0.50626329 -0.50626329  1.90988701 ... -0.11298948 -0.3433473
  -0.75036767]
 [ 0.50626329 -0.50626329 -0.52359118 ... -0.11298948 -0.3433473
   1.01363422]
 [ 0.50626329 -0.50626329 -0.52359118 ... -0.11298948 -0.3433473
  -0.18498245]
 ...
 [ 0.50626329 -0.50626329 -0.52359118 ... -0.11298948  1.97231083
   0.74224931]
 [ 0.50626329 -0.50626329 -0.52359118 ... -0.11298948 -0.3433473
   0.9684034 ]
 [ 0.50626329 -0.50626329 -0.52359118 ... -0.11298948 -0.3433473
   0.87794177]]


In [20]:
print(X_test)

[[ 0.50626329 -0.50626329 -0.52359118 ... -0.11298948 -0.3433473
  -0.02667458]
 [-1.97525678  1.97525678 -0.52359118 ... -0.11298948 -0.3433473
  -0.5694444 ]
 [ 0.50626329 -0.50626329  1.90988701 ... -0.11298948 -0.3433473
  -1.11221421]
 ...
 [ 0.50626329 -0.50626329 -0.52359118 ... -0.11298948 -0.3433473
   1.01363422]
 [ 0.50626329 -0.50626329 -0.52359118 ... -0.11298948 -0.3433473
   0.99101881]
 [ 0.50626329 -0.50626329 -0.52359118 ... -0.11298948 -0.3433473
  -0.0719054 ]]


In [25]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [26]:
y_pred = regressor.predict(X_test)

In [27]:
print(y_pred)

[0.80039442 0.85349501 0.78647841 0.73559544 0.57829637 0.64857963
 0.79131036 0.65448987 0.7522987  0.58823623 0.75773084 0.66228203
 0.54519497 0.7045794  0.43418284 0.81520562 0.70141575 0.58569307
 0.55786106 0.720947   0.70188238 0.6234942  0.59316479 0.75847851
 0.62901788 0.85750298 0.69447742 0.72924776 0.87524388 0.72634731
 0.7848864  0.75317356 0.7663063  0.81167574 0.77627535 0.79028294
 0.81909151 0.64836537 0.86396252 0.7461189  0.54652821 0.87480646
 0.79614229 0.76304089 0.75399688 0.74912488 0.78306045 0.77709935
 0.84782383 0.56107492 0.87325006 0.82148206 0.74626132 0.6674948
 0.76489231 0.70981826 0.89826937 0.86631238 0.86020886 0.57983372
 0.81973238 0.76403782 0.7748105  0.80562311 0.64721653 0.80658949
 0.70616632 0.71757987 0.77524792 0.67211885 0.57621164 0.66411309
 0.80840021 0.69247344 0.58602813 0.89336112 0.66308565 0.72173026
 0.72141492 0.8356931  0.72316968 0.53478978 0.68710299 0.64916966
 0.80622835 0.5396821  0.75773084 0.68075469 0.87610343 0.65263

In [32]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.020770392153408274


In [34]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

R-squared: 0.2859951724013309
