<a href="https://colab.research.google.com/github/sir-iko/sir-iko/blob/main/Taiwanese_bankruptcy_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
!pip install scikit-learn==1.2.0 --upgrade

In [3]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, 1:95].values
y = dataset.iloc[:, 0].values

In [4]:
print(X)

[[0.37059426 0.42438945 0.40574977 ... 0.02660063 0.56405011 1.        ]
 [0.46429094 0.53821413 0.51673002 ... 0.26457682 0.57017495 1.        ]
 [0.42607127 0.49901875 0.47229509 ... 0.02655472 0.56370608 1.        ]
 ...
 [0.47272461 0.533744   0.52063815 ... 0.02679116 0.5651584  1.        ]
 [0.50626432 0.5599106  0.55404465 ... 0.02682205 0.56530151 1.        ]
 [0.49305319 0.57010467 0.54954762 ... 0.02679295 0.56516694 1.        ]]


In [5]:
print(y)

[1 1 1 ... 0 0 0]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
print(X_train)

[[0.48242578 0.54862625 0.5373414  ... 0.04009788 0.56982652 1.        ]
 [0.49524692 0.56209115 0.54355158 ... 0.0268312  0.56534236 1.        ]
 [0.53414908 0.58558657 0.580545   ... 0.02687098 0.56551228 1.        ]
 ...
 [0.54604397 0.60940907 0.59617753 ... 0.02680168 0.56520808 1.        ]
 [0.50543558 0.58291539 0.55356282 ... 0.02680286 0.56521359 1.        ]
 [0.59181982 0.63797427 0.63140425 ... 0.02681077 0.56525022 1.        ]]


In [8]:
print(y_train)

[0 0 0 ... 0 0 0]


In [9]:
print(X_test)

[[0.48120704 0.46941779 0.5131431  ... 0.02670861 0.56473147 1.        ]
 [0.50182811 0.55789359 0.55270625 ... 0.02679116 0.5651584  1.        ]
 [0.51757422 0.53750545 0.55988008 ... 0.02688155 0.56555545 1.        ]
 ...
 [0.51557549 0.57288487 0.56651855 ... 0.02680056 0.56520285 1.        ]
 [0.4738946  0.53837767 0.525617   ... 0.02769607 0.56748281 1.        ]
 [0.55238142 0.61055386 0.59997859 ... 0.02681968 0.56529084 1.        ]]


In [10]:
print(y_test)

[0 0 0 ... 0 0 0]


In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train)

[[-0.37473336 -0.14848804 -0.26276953 ...  0.76296375  0.38247208
   0.        ]
 [-0.15951126  0.06033121 -0.15978527 ... -0.04260119 -0.00264054
   0.        ]
 [ 0.49352005  0.42470811  0.45368134 ... -0.04018583  0.01195196
   0.        ]
 ...
 [ 0.69319378  0.79415754  0.71291759 ... -0.04439365 -0.01417288
   0.        ]
 [ 0.01152075  0.38328243  0.00623247 ... -0.04432205 -0.01369996
   0.        ]
 [ 1.46161032  1.23715869  1.29708695 ... -0.04384167 -0.0105541
   0.        ]]


In [13]:
print(X_test)

[[-0.39519174 -1.37688626 -0.66405304 ... -0.0500448  -0.05510627
   0.        ]
 [-0.04903604 -0.00476629 -0.00797226 ... -0.04503271 -0.01844023
   0.        ]
 [ 0.21528616 -0.32095413  0.11099232 ... -0.03954392  0.01565986
   0.        ]
 ...
 [ 0.18173442  0.22772477  0.22107895 ... -0.04446163 -0.01462277
   0.        ]
 [-0.51794198 -0.30742738 -0.45719672 ...  0.0099147   0.18118701
   0.        ]
 [ 0.79957733  0.8119114   0.77595106 ... -0.04330058 -0.00706564
   0.        ]]


In [18]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [19]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [20]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.92 %
Standard Deviation: 0.41 %


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1307   11]
 [  36   10]]


0.9655425219941349

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1318
           1       0.48      0.22      0.30        46

    accuracy                           0.97      1364
   macro avg       0.72      0.60      0.64      1364
weighted avg       0.96      0.97      0.96      1364

